import { yekan } from "@/utils/font";
import "./globals.css";
import Footer from "@/layout/Footer";
import Header from "@/layout/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
